Models/Sprzet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace myRemiza.Models
{
    public partial class Sprzet
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Firma { get; set; }
        public string Rodzaj { get; set; }
        public string Nr_seryjny { get; set; }
        [Column("MagazynId")]
        public int MagazynId { get; set; }
        [DataType(DataType.Date)]
        public DateTime Data_pozyskania { get; set; }
        [DataType(DataType.Date)]
        public DateTime Data_Przegladu { get; set; }

        public virtual Magazyn Magazyn { get; set; }
        public virtual Samochody Samochody { get; set; }
    }
}

Controllers/SprzetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using myRemiza.Data;
using myRemiza.Models;

namespace myRemiza.Controllers
{
    [Authorize(Roles = "Basic")]
    public class SprzetController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SprzetController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Sprzet
        public async Task<IActionResult> Index(string searchString)
        {
            var applicationDbContext = _context.Sprzet.Include(s => s.Magazyn).Include(w => w.Samochody).OrderBy(m=>m.Data_Przegladu);
            if (!String.IsNullOrEmpty(searchString))
            {
                applicationDbContext = (IOrderedQueryable<Sprzet>)applicationDbContext.Where(s => s.Firma!.Contains(searchString) || s.Rodzaj!.Contains(searchString) || s.Nazwa!.Contains(searchString));
            }
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Sprzet/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sprzet = await _context.Sprzet
                .Include(s => s.Magazyn)
                .Include(s => s.Samochody)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sprzet == null)
            {
                return NotFound();
            }

            return View(sprzet);
        }

        // GET: Sprzet/Create
        public IActionResult Create()
        {
            ViewBag.Samochody = _context.Samochody.ToDictionary(u => u.Id, u => u.Typ);
            ViewBag.Magazyn = _context.Magazyn.ToDictionary(u => u.Id, u => u.Nazwa);

            return View();
        }
        // POST: Sprzet/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nazwa,Firma,Rodzaj,Nr_seryjny,MagazynId,Data_pozyskania,Data_Przegladu")] Sprzet sprzet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sprzet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MagazynId"] = new SelectList(_context.Magazyn, "Id", "Id", sprzet.MagazynId);
            ViewData["MagazynId"] = new SelectList(_context.Samochody, "Id", "Id", sprzet.MagazynId);
            return View(sprzet);
        }

        // GET: Sprzet/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sprzet = await _context.Sprzet.FindAsync(id);
            if (sprzet == null)
            {
                return NotFound();
            }
            ViewBag.Samochody = _context.Samochody.ToDictionary(u => u.Id, u => u.Typ);
            ViewBag.Magazyn = _context.Magazyn.ToDictionary(u => u.Id, u => u.Nazwa);
            return View(sprzet);
        }

        // POST: Sprzet/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nazwa,Firma,Rodzaj,Nr_seryjny,MagazynId,Data_pozyskania,Data_Przegladu")] Sprzet sprzet)
        {
            if (id != sprzet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sprzet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SprzetExists(sprzet.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MagazynId"] = new SelectList(_context.Magazyn, "Id", "Id", sprzet.MagazynId);
            ViewData["MagazynId"] = new SelectList(_context.Samochody, "Id", "Id", sprzet.MagazynId);
            return View(sprzet);
        }

        // GET: Sprzet/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sprzet = await _context.Sprzet
                .Include(s => s.Magazyn)
                .Include(s => s.Samochody)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sprzet == null)
            {
                return NotFound();
            }

            return View(sprzet);
        }

        // POST: Sprzet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sprzet = await _context.Sprzet.FindAsync(id);
            _context.Sprzet.Remove(sprzet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SprzetExists(int id)
        {
            return _context.Sprzet.Any(e => e.Id == id);
        }
    }
}

Views/Sprzet/Create.cshtml
@model myRemiza.Models.Sprzet

@{
    ViewData["Title"] = "Create";
}

<h1>Dodaj nowy sprzęt</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nazwa" class="control-label">Nazwa</label>
                <input asp-for="Nazwa" class="form-control" />
                <span asp-validation-for="Nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Firma" class="control-label">Firma</label>
                <input asp-for="Firma" class="form-control" />
                <span asp-validation-for="Firma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rodzaj" class="control-label">Rodzaj</label>
                <input asp-for="Rodzaj" class="form-control" />
                <span asp-validation-for="Rodzaj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nr_seryjny" class="control-label">Numer seryjny</label>
                <input asp-for="Nr_seryjny" class="form-control" />
                <span asp-validation-for="Nr_seryjny" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MagazynId" class="control-label">Miejsce przechowywania</label>
                <select asp-for="MagazynId" class="form-control" asp-items="@(new SelectList(ViewBag.Magazyn, "Key", "Value"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="Data_pozyskania" class="control-label">Data pozyskania</label>
                <input asp-for="Data_pozyskania" class="form-control" />
                <span asp-validation-for="Data_pozyskania" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data_Przegladu" class="control-label">Data kolejnego przeglądu</label>
                <input asp-for="Data_Przegladu" class="form-control" />
                <span asp-validation-for="Data_Przegladu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Sprzet/Delete.cshtml
@model myRemiza.Models.Sprzet

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sprzet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazwa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Firma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rodzaj)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rodzaj)
        </dd>
        <dt class = "col-sm-2">
            Numer seryjny
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nr_seryjny)
        </dd>
        <dt class = "col-sm-2">
            Data pozyskania
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data_pozyskania)
        </dd>
        <dt class = "col-sm-2">
            Data kolejnego przeglądu
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data_Przegladu)
        </dd>
        <dt class = "col-sm-2">
            Miejsce przechowywania
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Magazyn.Nazwa)
            @Html.DisplayFor(model => model.Samochody.Typ)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> |
        <a asp-action="Index">Powrót</a>
    </form>
</div>

Views/Sprzet/Details.cshtml
@model myRemiza.Models.Sprzet

@{
    ViewData["Title"] = "Details";
}

<h1>Szczegóły</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazwa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Firma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rodzaj)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rodzaj)
        </dd>
        <dt class = "col-sm-2">
            Numer seryjny
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nr_seryjny)
        </dd>
        <dt class = "col-sm-2">
            Data pozyskania
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data_pozyskania)
        </dd>
        <dt class = "col-sm-2">
            Data kolejnego przeglądu
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data_Przegladu)
        </dd>
        <dt class = "col-sm-2">
            Miejsce przechowywania
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Magazyn.Nazwa)
            @Html.DisplayFor(model => model.Samochody.Typ)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edytuj</a> |
    <a asp-action="Index">Powrót</a>
</div>

Views/Sprzet/Edit.cshtml
@model myRemiza.Models.Sprzet

@{
    ViewData["Title"] = "Edit";
}

<h1>Edytuj</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nazwa" class="control-label">Nazwa</label>
                <input asp-for="Nazwa" class="form-control" />
                <span asp-validation-for="Nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Firma" class="control-label">Firma</label>
                <input asp-for="Firma" class="form-control" />
                <span asp-validation-for="Firma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rodzaj" class="control-label">Rodzaj</label>
                <input asp-for="Rodzaj" class="form-control" />
                <span asp-validation-for="Rodzaj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nr_seryjny" class="control-label">Numer seryjny</label>
                <input asp-for="Nr_seryjny" class="form-control" />
                <span asp-validation-for="Nr_seryjny" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Data_pozyskania" class="control-label">Data pozyskania</label>
                <input asp-for="Data_pozyskania" class="form-control" />
                <span asp-validation-for="Data_pozyskania" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data_Przegladu" class="control-label">Data przeglądu</label>
                <input asp-for="Data_Przegladu" class="form-control" />
                <span asp-validation-for="Data_Przegladu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MagazynId" class="control-label">Miejsce przechowywania</label>
                <select asp-for="MagazynId" class="form-control" asp-items="@(new SelectList(ViewBag.Magazyn, "Key", "Value"))"></select>
                <span asp-validation-for="MagazynId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Sprzet/Index.cshtml
@model IEnumerable<myRemiza.Models.Sprzet>

@{
    ViewData["Title"] = "Index";
}

<h1>Sprzęt należący do jeddnostki</h1>

<p>
    <a asp-action="Create">Dodaj nowy</a>
</p>
<form asp-controller="Sprzet" asp-action="Index" method="get">
    <p>
        Znajdź: <input type="text" name="SearchString" />
        <input type="submit" value="Szukaj" />
        <input type="submit" value="Powrót" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nazwa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Firma)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rodzaj)
            </th>
            <th>
                Numer seryjny
            </th>
            <th>
                Data kolejnego przeglądu
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Firma)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rodzaj)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nr_seryjny)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data_Przegladu)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edytuj</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Szczegóły</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
            </td>
        </tr>
}
    </tbody>
</table>