Models/Wyjazdy.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace myRemiza.Models
{
    public partial class Wyjazdy
    {
        public int Id { get; set; }
        public DateTime Data { get; set; }
        public string Miejsce { get; set; }
        [Column("Rodzaj_zdarzeniaId")]
        public int Rodzaj_zdarzeniaId { get; set; }
        public string Strazacy { get; set; }
        [Column("SamochodyId")]
        public int SamochodyId { get; set; }
        [Column("SamochodyId2")]
        public int SamochodyId2 { get; set; }
        public string Opis { get; set; }

        public virtual Samochody Samochody { get; set; }
        public virtual Rodzaj_zdarzenia Rodzaj_zdarzenia { get; set; }
    }
}

Controllers/WyjazdyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using myRemiza.Data;
using myRemiza.Enums;
using myRemiza.Models;

namespace myRemiza.Controllers
{
    [Authorize(Roles = "Basic")]
    public class WyjazdyController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WyjazdyController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Wyjazdy
        public async Task<IActionResult> Index(string searchString)
        {
            var applicationDbContext = _context.Wyjazdy.Include(w => w.Rodzaj_zdarzenia).Include(w => w.Samochody).OrderByDescending(w => w.Data);
            if (!String.IsNullOrEmpty(searchString))
            {
                applicationDbContext = (IOrderedQueryable<Wyjazdy>)applicationDbContext.Where(s => s.Opis!.Contains(searchString)|| s.Miejsce!.Contains(searchString) || s.Strazacy!.Contains(searchString));
                
            }
            return View(await applicationDbContext.ToListAsync());
        }
        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }
        // GET: Wyjazdy/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wyjazdy = await _context.Wyjazdy
                .Include(w => w.Rodzaj_zdarzenia)
                .Include(w => w.Samochody)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (wyjazdy == null)
            {
                return NotFound();
            }

            return View(wyjazdy);
        }

        // GET: Wyjazdy/Create
        public IActionResult Create()
        {
            ViewBag.Rodzaj_zdarzenia = _context.Rodzaj_zdarzenia.ToDictionary(u => u.Id, u => u.Nazwa);
            ViewBag.Samochody = _context.Samochody.ToDictionary(u => u.Id, u => u.Typ);
            return View();
        }

        // POST: Wyjazdy/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Data,Miejsce,Rodzaj_zdarzeniaId,Strazacy,SamochodyId,SamochodyId2,Opis")] Wyjazdy wyjazdy)
        {
            if (ModelState.IsValid)
            {
                _context.Add(wyjazdy);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Rodzaj_zdarzeniaId"] = new SelectList(_context.Rodzaj_zdarzenia, "Id", "Id", wyjazdy.Rodzaj_zdarzeniaId);
            ViewData["SamochodyId"] = new SelectList(_context.Samochody, "Id", "Id", wyjazdy.SamochodyId);
            ViewData["SamochodyId2"] = new SelectList(_context.Samochody, "Id", "Id", wyjazdy.SamochodyId);
            return View(wyjazdy);
        }

        // GET: Wyjazdy/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wyjazdy = await _context.Wyjazdy.FindAsync(id);
            if (wyjazdy == null)
            {
                return NotFound();
            }
            ViewBag.Rodzaj_zdarzenia = _context.Rodzaj_zdarzenia.ToDictionary(u => u.Id, u => u.Nazwa);
            ViewBag.Samochody = _context.Samochody.ToDictionary(u => u.Id, u => u.Typ);
            return View(wyjazdy);
        }

        // POST: Wyjazdy/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Data,Miejsce,Rodzaj_zdarzeniaId,Strazacy,SamochodyId,SamochodyId2,Opis")] Wyjazdy wyjazdy)
        {
            if (id != wyjazdy.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(wyjazdy);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WyjazdyExists(wyjazdy.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Rodzaj_zdarzeniaId"] = new SelectList(_context.Rodzaj_zdarzenia, "Id", "Id", wyjazdy.Rodzaj_zdarzeniaId);
            ViewData["SamochodyId"] = new SelectList(_context.Samochody, "Id", "Id", wyjazdy.SamochodyId);
            ViewData["SamochodyId2"] = new SelectList(_context.Samochody, "Id", "Id", wyjazdy.SamochodyId);
            return View(wyjazdy);
        }

        // GET: Wyjazdy/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wyjazdy = await _context.Wyjazdy
                .Include(w => w.Rodzaj_zdarzenia)
                .Include(w => w.Samochody)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (wyjazdy == null)
            {
                return NotFound();
            }

            return View(wyjazdy);
        }

        // POST: Wyjazdy/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var wyjazdy = await _context.Wyjazdy.FindAsync(id);
            _context.Wyjazdy.Remove(wyjazdy);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WyjazdyExists(int id)
        {
            return _context.Wyjazdy.Any(e => e.Id == id);
        }
    }
}

Views/Wyjazdy/Create.cshtml
@model myRemiza.Models.Wyjazdy

@{
    ViewData["Title"] = "Create";
}

<h1>Dodaj nowy wyjazd</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Data" class="control-label">Data</label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Miejsce" class="control-label">Miejsce</label>
                <input asp-for="Miejsce" class="form-control" />
                <span asp-validation-for="Miejsce" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rodzaj_zdarzeniaId" class="control-label">Rodzaj zdarzenia</label>
                <select asp-for="Rodzaj_zdarzeniaId" class ="form-control" asp-items="@(new SelectList(ViewBag.Rodzaj_zdarzenia, "Key", "Value"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="Strazacy" class="control-label">Strażacy uczestniczący w akcji</label>
                <textarea asp-for="Strazacy" class="form-control"></textarea>
                <span  asp-validation-for="Strazacy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SamochodyId" class="control-label">Wóz bojowy #1</label>
                <select asp-for="SamochodyId" class ="form-control" asp-items="@(new SelectList(ViewBag.Samochody, "Key", "Value"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="SamochodyId2" class="control-label">Wóz bojowy #2</label>
                <select asp-for="SamochodyId2" class="form-control" asp-items="@(new SelectList(ViewBag.Samochody, "Key", "Value"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label">Opis zdarzenia</label>
                <textarea asp-for="Opis" class="form-control"></textarea>
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Wyjazdy/Delete.cshtml
@model myRemiza.Models.Wyjazdy

@{
    ViewData["Title"] = "Delete";
}

<h1>Usuń wyjazd</h1>

<h3>Jesteś pewien, że chcesz usunąć ten wyjazd?</h3>
<div>
    <h4>Wyjazdy</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Miejsce)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Miejsce)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rodzaj_zdarzenia)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rodzaj_zdarzenia.Nazwa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Strazacy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Strazacy)
        </dd>
        <dt class="col-sm-2">
            Samochód bojowy #1
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Samochody.Typ)
        </dd>
        <dt class="col-sm-2">
            Samochód bojowy #2
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Samochody.Typ)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>


    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> |
        <a asp-action="Index">Powrót</a>
    </form>
</div>

Views/Wyjazdy/Details.cshtml
@model myRemiza.Models.Wyjazdy

@{
    ViewData["Title"] = "Details";
}

<h1>Szczegóły wyjazdu</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Miejsce)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Miejsce)
        </dd>

        <dt class="col-sm-2">
            Rodzaj zdarzenia
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rodzaj_zdarzenia.Nazwa)
        </dd>
        <dt class="col-sm-2">
            Strażacy uczestniczący w akcji
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Strazacy)
        </dd>
        <dt class="col-sm-2">
            Samochód bojwoy #1
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Samochody.Typ)
        </dd>
        <dt class="col-sm-2">
            Samochód bojwoy #2
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Samochody.Typ)
        </dd>
        <dt class="col-sm-2">
            Opis zdarzenia
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edytuj</a> |
    <a asp-action="Index">Powrót</a>
</div>

Views/Wyjazdy/Edit.cshtml
@model myRemiza.Models.Wyjazdy

@{
    ViewData["Title"] = "Edit";
}

<h1>Edytuj wyjazd</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Data" class="control-label">Data</label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Miejsce" class="control-label">Miejsce</label>
                <input asp-for="Miejsce" class="form-control" />
                <span asp-validation-for="Miejsce" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rodzaj_zdarzeniaId" class="control-label">Rodzaj zdarzenia</label>
                <select asp-for="Rodzaj_zdarzeniaId" class="form-control" asp-items="@(new SelectList(ViewBag.Rodzaj_zdarzenia, "Key", "Value"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="Strazacy" class="control-label">Strażacy uczestniczący w akcji</label>
                <input asp-for="Strazacy" class="form-control" />
                <span asp-validation-for="Strazacy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SamochodyId" class="control-label">Wóz bojowy #1</label>
                <select asp-for="SamochodyId" class="form-control" asp-items="@(new SelectList(ViewBag.Samochody, "Key", "Value"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="SamochodyId2" class="control-label">Wóz bojowy #2</label>
                <select asp-for="SamochodyId2" class="form-control" asp-items="@(new SelectList(ViewBag.Samochody, "Key", "Value"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label">Opis</label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Wyjazdy/Index.cshtml
@model IEnumerable<myRemiza.Models.Wyjazdy>

@{
    ViewData["Title"] = "Index";
}

<h1>Wyjazdy bojowe</h1>

<p>
    <a asp-action="Create">Dodaj nowy</a>
</p>
<form asp-controller="Wyjazdy" asp-action="Index" method="get">
    <p>
        Znajdź wyjazd: <input type="text" name="SearchString" />
        <input type="submit" value="Szukaj" />
        <input type="submit" value="Powrót" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Data
            </th>
            <th>
                Miejsce
            </th>
            <th>
                Rodzaj zdarzenia
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Miejsce)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rodzaj_zdarzenia.Nazwa)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edytuj</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Szczegóły</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
            </td>
        </tr>
}
    </tbody>
</table>